export const COUCHDB_ENTITY_METADATA = 'COUCHDB_ENTITY_METADATA';
export const COUCHDB_CONNECTION_TOKEN = 'COUCHDB_CONNECTION_TOKEN';
export const COUCHDB_REPOSITORY_FACTORY_TOKEN =
  'COUCHDB_REPOSITORY_FACTORY_TOKEN';
